### ISSUE TITLE
Issues of generating provider-jet-alibaba

### ISSUE THREAD

**Issue by zzxwill** [crossplane/terrajet#227] opened 2022-02-06 08:48 UTC
### What happened?

I tried to generate a Terraform provider in the repo https://github.com/zzxwill/provider-jet-alibaba and it failed.

```
➜  /Users/zhouzhengi/Programming/golang/src/github.com/zzxwill/provider-jet-alibaba git:(main) ✗ make generate
16:42:06 [ .. ] verify dependencies have expected content
all modules verified
16:42:21 [ OK ] go modules dependencies verified
16:42:22 [ .. ] go generate darwin_amd64
go: downloading github.com/turkenh/terraform-plugin-sdk v1.17.2-patch1
# github.com/hashicorp/terraform-plugin-sdk/internal/configs/configload
../.work/pkg/pkg/mod/github.com/turkenh/terraform-plugin-sdk@v1.17.2-patch1/internal/configs/configload/loader_snapshot.go:52:29: cannot use fs (type snapshotFS) as type afero.Fs in argument to configs.NewParser:
	snapshotFS does not implement afero.Fs (missing Chown method)
../.work/pkg/pkg/mod/github.com/turkenh/terraform-plugin-sdk@v1.17.2-patch1/internal/configs/configload/loader_snapshot.go:57:28: cannot use fs (type snapshotFS) as type afero.Fs in field value:
	snapshotFS does not implement afero.Fs (missing Chown method)
../.work/pkg/pkg/mod/github.com/turkenh/terraform-plugin-sdk@v1.17.2-patch1/internal/configs/configload/loader_snapshot.go:200:5: cannot use snapshotFS{} (type snapshotFS) as type afero.Fs in assignment:
	snapshotFS does not implement afero.Fs (missing Chown method)
apis/generate.go:32: running "go": exit status 2
16:42:39 [FAIL]
make[1]: *** [go.generate] Error 1
make: *** [generate] Error 2
```

### How can we reproduce it?

1. Clone https://github.com/zzxwill/provider-jet-alibaba.git
2. run `make generate`

**Comment by turkenh** [comment] 2022-02-07 09:42
@zzxwill adding the following replace to your `go.mod` should help:

```
replace github.com/spf13/afero => github.com/spf13/afero v1.2.2
```

**Comment by zzxwill** [comment] 2022-02-07 11:01
@turkenh Thanks. I have added the line. But I hit another issue.

```
➜  provider-jet-alibaba git:(main) ✗ make generate
17:59:58 [ .. ] verify dependencies have expected content
all modules verified
18:00:42 [ OK ] go modules dependencies verified
18:00:45 [ .. ] go generate darwin_amd64
panic: interface conversion: interface {} is schema.ValueType, not schema.ValueType (types from different packages)

goroutine 1 [running]:
github.com/crossplane/terrajet/pkg/types/conversion.toV2Schema(0xc000a077c0, 0xc000bfd020)
	/Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/provider-jet-alibaba/.work/pkg/pkg/mod/github.com/crossplane/terrajet@v0.3.2/pkg/types/conversion/conversion.go:82 +0x5c5
github.com/crossplane/terrajet/pkg/types/conversion.toV2Resource(0xc00085abe0, 0xc0010c0c90)
	/Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/provider-jet-alibaba/.work/pkg/pkg/mod/github.com/crossplane/terrajet@v0.3.2/pkg/types/conversion/conversion.go:41 +0xf7
github.com/crossplane/terrajet/pkg/types/conversion.GetV2ResourceMap(0x7ff35f8, 0xc000454280, 0xc000ab4180)
	/Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/provider-jet-alibaba/.work/pkg/pkg/mod/github.com/crossplane/terrajet@v0.3.2/pkg/types/conversion/conversion.go:32 +0x117
main.main()
	/Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/provider-jet-alibaba/cmd/generator/main.go:48 +0x7d
exit status 2
apis/generate.go:32: running "go": exit status 1
18:02:31 [FAIL]
make[1]: *** [go.generate] Error 1
make: *** [generate] Error 2
```

**Comment by zzxwill** [comment] 2022-02-07 11:05
@zzxwill The repo for Alibaba Cloud https://github.com/zzxwill/provider-jet-alibaba.git is the latest with your suggested fix.

**Comment by bretagne-peiqi** [comment] 2022-02-14 02:03
@turkenh  hello, could we fix this bug in this days. we are also evaluating this solution to generate provider-jet-alibaba

**Comment by bretagne-peiqi** [comment] 2022-02-14 06:48
<img width="814" alt="panic" src="https://user-images.githubusercontent.com/5621794/153813862-2836d3ff-f835-40ac-8870-b56115bdaf00.png">

I meet the same problem

**Comment by turkenh** [comment] 2022-02-16 10:41
Sorry, I missed this issue probably due to the title is no longer relevant.

Just reproduced and debugged on my side a bit and it seems to be the problem is the terraform provider using a very old SDK version, `v1.4.0`, where there is `v1.17.2` available as the latest v1 version. 

I believe this issue could still be with some workaround without the terraform provider upgrading the version, however, I don't think it is worth spending time on it. 

Importing terraform provider codebase is already something problematic and something that [we are about to deprecate](https://github.com/crossplane/terrajet/pull/174). So, I will hold off trying to find a workaround for this issue and will close this once I verify generating the Alibaba provider with the new approach is possible.

**Comment by turkenh** [comment] 2022-02-21 10:56
@zzxwill and @bretagne-peiqi just merged the said changes. I've also code generation part with provider-alibaba but couldn't test at runtime as I don't have an account.

I would suggest you start fresh following the updated (simplified) [provider generation guide](https://github.com/crossplane/terrajet/blob/main/docs/generating-a-provider.md) and the latest [provider-jet-template](https://github.com/crossplane-contrib/provider-jet-template) repo. 

Also, I would love to hear any issues/feedback regarding the new experience as you will be the first ones testing this approach other than me 😊

**Comment by zzxwill** [comment] 2022-02-22 02:36
@turkenh Great, I will try. Thanks.

**Comment by bretagne-peiqi** [comment] 2022-02-23 01:11
@zzxwill Hi, have you tested the new version. does it work well? we are planning to use it as our solution

**Comment by bretagne-peiqi** [comment] 2022-02-24 09:15
@turkenh Hello, I generated the provider but have some problems:

<img width="792" alt="1645694039(1)" src="https://user-images.githubusercontent.com/5621794/155494570-7e286638-d61b-4ad6-bd73-52b23b642a21.png">

<img width="498" alt="1645693978(1)" src="https://user-images.githubusercontent.com/5621794/155494590-77dcbb44-d12c-43ca-a4d9-81c29c658634.png">

do you have some idea.  I edited cmd/provider/main.go  controller.Setup ==> providerconfig.Setup

**Comment by bretagne-peiqi** [comment] 2022-02-24 10:08
@turkenh, hello, what's the purpose for config/schema.json;  I compared Crossplane/alibaba-provider with generated Alibaba-provider using terrajet.  I don't understand how the generated provider works. It lacks update/create/delete methods ?? besides, I don't understand how clients connect and communication with alicloud APIs, I don't see the methods.

thanks.

**Comment by turkenh** [comment] 2022-02-24 10:21
> @turkenh, hello, what's the purpose for config/schema.json; I compared Crossplane/alibaba-provider with generated Alibaba-provider using terrajet. I don't understand how the generated provider works. It lacks update/create/delete methods ?? besides, I don't understand how clients connect and communication with alicloud APIs, I don't see the methods.
> 
> thanks.

Does this mean you could successfully generate? 🙂 

I would suggest you check our [Terrajet deep dive series](https://blog.crossplane.io/deep-dive-terrajet-part-i/) to learn more about how it works. 
For example, you can check [this section](https://blog.crossplane.io/deep-dive-terrajet-part-ii/) to understand the controller part.

**Comment by zzxwill** [comment] 2022-02-25 03:01
@bretagne-peiqi @turkenh Everything looks fine except failing to generate resources (CRD) for newly added Terraform resources `alicloud_vpc` and `alicloud_oss_bucket`. Did I miss any configuration?

The new test repo is https://github.com/zzxwill/provider-jet-alibaba2.git, and the result of `make generate` is as below.

```
➜  provider-jet-alibaba2 git:(main) ✗ make generate
10:56:51 [ .. ] generating provider schema for hashicorp/null 3.1.0
10:56:54 [ OK ] generating provider schema for hashicorp/null 3.1.0
10:56:54 [ .. ] verify dependencies have expected content
all modules verified
10:56:59 [ OK ] go modules dependencies verified
10:56:59 [ .. ] go generate darwin_amd64

Generated 0 resources!
10:57:20 [ OK ] go generate darwin_amd64
10:57:20 [ .. ] go mod tidy
10:57:23 [ OK ] go mod tidy
```

**Comment by turkenh** [comment] 2022-02-25 06:57
@zzxwill did you follow all steps in the guide till `make generate`? Asking because [these lines](https://github.com/zzxwill/provider-jet-alibaba2/blob/main/Makefile#L9-L12) should have been replaced with your provider.

**Comment by zzxwill** [comment] 2022-02-25 07:04
> @zzxwill did you follow all steps in the guide till `make generate`? Asking because [these lines](https://github.com/zzxwill/provider-jet-alibaba2/blob/main/Makefile#L9-L12) should have been replaced with your provider.

No, I thought you made a mistake in the guide as the syntax is wrong for export and I was about to raise an issue.
```
export TERRAFORM_PROVIDER_SOURCE=aliyun/alicloud
export TERRAFORM_PROVIDER_VERSION=1.157.0
export TERRAFORM_PROVIDER_DOWNLOAD_NAME=terraform-provider-alicloud
export TERRAFORM_PROVIDER_DOWNLOAD_URL_PREFIX=https://releases.hashicorp.com/terraform-provider-alicloud/1.157.0
```

Sorry, let me change the makefile. Thanks.

**Comment by turkenh** [comment] 2022-02-25 07:08
No worries. 
I agree that it looks like it is expected to be pasted to the terminal unless you read instructions carefully, I was also caught in the same trap couple of times :)

Feel free to open a PR if you have any idea to make it more explicit.

**Comment by zzxwill** [comment] 2022-02-25 07:48
@turkenh I successfully created resources with your guide, thanks. 
By testing with Alibaba Cloud VPC, it succeeded.

```
➜  providerconfig git:(main) ✗ k get vpcs.vpc.alicloud.jet.crossplane.io
NAME      READY   SYNCED   EXTERNAL-NAME               AGE
example   True    False    vpc-2zegc9hgtyeyis96d7bov   21m
➜  providerconfig git:(main) ✗ aliyun vpc DescribeVpcAttribute --VpcId vpc-2zegc9hgtyeyis96d7bov
{
	"CidrBlock": "172.16.0.0/12",
	"CloudResources": {
		"CloudResourceSetType": [
			{
				"ResourceCount": 1,
				"ResourceType": "VRouter"
			},
			{
				"ResourceCount": 1,
				"ResourceType": "RouteTable"
			}
		]
	},
	"CreationTime": "2022-02-25T07:44:24Z",
	"Description": "",
	"Ipv4GatewayId": "",
	"Ipv6CidrBlock": "",
	"IsDefault": false,
	"NetworkAclNum": 0,
	"OwnerId": 1874279259696164,
	"RegionId": "cn-beijing",
	"RequestId": "F8AAAB31-75FA-5DBB-B86F-1599AC96A408",
	"ResourceGroupId": "rg-acfm3s5kf5r6yja",
	"SecondaryCidrBlocks": {
		"SecondaryCidrBlock": []
	},
	"Status": "Available",
	"SupportIpv4Gateway": false,
	"UserCidrs": {
		"UserCidr": []
	},
	"VRouterId": "vrt-2zekj3mo5ryh2kqp0jvu8",
	"VSwitchIds": {
		"VSwitchId": []
	},
	"VpcId": "vpc-2zegc9hgtyeyis96d7bov",
	"VpcName": "vpc-2zegc9hgtyeyis96d7bov"
}
```

**Comment by bretagne-peiqi** [comment] 2022-02-25 08:33
@turkenh @zzxwill   do we have a fix format for resource template ? for example  alicloud_instance, alicloud_cs_kubernetes.
<img width="463" alt="Screen Shot 2022-02-25 at 4 32 39 PM" src="https://user-images.githubusercontent.com/5621794/155682177-0678419e-5fa3-4fd3-9821-2a1973eaa98b.png">

how can we create these config files quickly without looking into apis...

**Comment by bretagne-peiqi** [comment] 2022-02-28 01:58
@turkenh @zzxwill Hello do we have a solution to support under_score in resource name from alicloud terraform provider? 
like cs_kubernetes.  or do we have a translation rule from terraform provider to eliminate under_scores ?

**Comment by zzxwill** [comment] 2022-02-28 02:57
@bretagne-peiqi Generally, these docs/tables can help https://github.com/crossplane/terrajet/issues/245.

But in fact, it's pretty difficult to set those values for complex cloud resources, like ecs/rds/ack, even we checked the usage docs/tables very carefully. In Terraform, we use preconfigured Terraform modules to simply the properties set.

**Comment by bretagne-peiqi** [comment] 2022-03-18 09:36
./provider --terraform-provider-source=aliyun/alicloud  --terraform-provider-version=1.155.0  --terrorm-version=1.1.5 --debug

I am testing of creating a securitygroup resource in alicloud. but it seems failed to get terraform-alicloud-provier. Can we set the waittime before it succeed to get. Or if we download the provider mannually, where should we put for terraform to pilot.


![image](https://user-images.githubusercontent.com/5621794/158977898-d9a19975-ee9c-49df-a29f-7cace8f3ef25.png)

**Comment by bretagne-peiqi** [comment] 2022-03-21 04:31
@zzxwill @turkenh need a methodology to debug and find workable resourceconfig examples.

I am recently testing ecs, managedk8s resources using crossplane-provider generated with alicloud-provider version 1.155.0,  terraform version 1.1.5.

 my config:
![image](https://user-images.githubusercontent.com/5621794/159205480-a54f93b6-3206-4a8f-8abd-41c448c0983d.png)
![image](https://user-images.githubusercontent.com/5621794/159205516-18809f81-cf9a-445c-832e-c89f56247f54.png)

logs:
![image](https://user-images.githubusercontent.com/5621794/159205580-14865274-025c-4757-88ba-412a361080cf.png)

for ecs creation, logs say no type named "name", I don't understand because I have no type name in my config.
for managedk8s creation, "refusing to modify uncontrolled secret of type "Opaque"" ??

do you have a method to debug or have any of you experienced ?

**Comment by turkenh** [comment] 2022-04-08 11:49
> @turkenh I successfully created resources with your guide, thanks. By testing with Alibaba Cloud VPC, it succeeded.
> 
> ```
> ➜  providerconfig git:(main) ✗ k get vpcs.vpc.alicloud.jet.crossplane.io
> NAME      READY   SYNCED   EXTERNAL-NAME               AGE
> example   True    False    vpc-2zegc9hgtyeyis96d7bov   21m
> ➜  providerconfig git:(main) ✗ aliyun vpc DescribeVpcAttribute --VpcId vpc-2zegc9hgtyeyis96d7bov
> {
> 	"CidrBlock": "172.16.0.0/12",
> 	"CloudResources": {
> 		"CloudResourceSetType": [
> 			{
> 				"ResourceCount": 1,
> 				"ResourceType": "VRouter"
> 			},
> 			{
> 				"ResourceCount": 1,
> 				"ResourceType": "RouteTable"
> 			}
> 		]
> 	},
> 	"CreationTime": "2022-02-25T07:44:24Z",
> 	"Description": "",
> 	"Ipv4GatewayId": "",
> 	"Ipv6CidrBlock": "",
> 	"IsDefault": false,
> 	"NetworkAclNum": 0,
> 	"OwnerId": 1874279259696164,
> 	"RegionId": "cn-beijing",
> 	"RequestId": "F8AAAB31-75FA-5DBB-B86F-1599AC96A408",
> 	"ResourceGroupId": "rg-acfm3s5kf5r6yja",
> 	"SecondaryCidrBlocks": {
> 		"SecondaryCidrBlock": []
> 	},
> 	"Status": "Available",
> 	"SupportIpv4Gateway": false,
> 	"UserCidrs": {
> 		"UserCidr": []
> 	},
> 	"VRouterId": "vrt-2zekj3mo5ryh2kqp0jvu8",
> 	"VSwitchIds": {
> 		"VSwitchId": []
> 	},
> 	"VpcId": "vpc-2zegc9hgtyeyis96d7bov",
> 	"VpcName": "vpc-2zegc9hgtyeyis96d7bov"
> }
> ```

@zzxwill I am closing this issue based on your comment above. 
Feel free to create another issue if there are any other problems you're observing.

Thanks!

**Closed by turkenh** 2022-04-08 11:49 UTC
Labels: bug
